CREATE TEMPORARY TABLE DIMENSOES AS
(
	SELECT
		ID_DIMENSAO_PROGRAMA
	FROM
		TD_PROGRAMA
	WHERE
		DATA_CRIACAO = DATE(NOW())
	UNION
    SELECT
		ID_DIMENSAO_ORGAO
	FROM
		TD_ORGAO
	WHERE
		DATA_CRIACAO = DATE(NOW())
	UNION
	SELECT
		ID_DIMENSAO_AREA_ATUACAO
	FROM
		TD_AREA_ATUACAO
	WHERE
		DATA_CRIACAO = DATE(NOW())
	UNION
    SELECT
	ID_DATA_DIMENSAO
	FROM
		TD_DATA
	WHERE
		DATA_CRIACAO = DATE(NOW())
);


INSERT INTO FT_DESPESAS_PUBLICAS
(
	VL_ORCADO
,	VL_LIQUIDADO
,	ID_DIMENSAO_PROGRAMA
,	ID_DIMENSAO_ORGAO
,	ID_DIMENSAO_AREA_ATUACAO
,	ID_DIMENSAO_DATA
)
SELECT 0.0, 0.0, D.ID_DIMENSAO_PROGRAMA, D.ID_DIMENSAO_ORGAO, D.ID_DIMENSAO_AREA_ATUACAO, D.ID_DIMENSAO_DATA  FROM DIMENSOES AS D;